# Generated by Django 4.1.1 on 2023-03-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_menuitem_parent_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="url",
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
